server:
  port: 8080

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    #注册到eureka中  默认为ture
    register-with-eureka: true
    #是否从eurekaServer中抓取信息，单点无所谓，集群必须为true才能配合ribbon使用负载均衡，默认为true
    fetch-registry: true
  instance:
    instance-id: cloud-order-service
    prefer-ip-address: true