server:
  port: 9527

spring:
  application:
    name: cloud-gateway-gateway9527
  cloud:
    gateway:
      routes:
        - id: payment_routh #\u8DEF\u7531\u7684id \u6CA1\u6709\u56FA\u5B9A\u89C4\u5219\u4F46\u8981\u6C42\u552F\u4E00\uFF0C\u5EFA\u8BAE\u914D\u5408\u670D\u52A1\u540D
          #uri: http://127.0.0.1:8001
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/getPayment/**  #\u65AD\u8A00\uFF0C\u8DEF\u5F84\u76F8\u5339\u914D\u7684\u8FDB\u884C\u8DEF\u7531

        - id: payment_routh2 #\u8DEF\u7531\u7684id \u6CA1\u6709\u56FA\u5B9A\u89C4\u5219\u4F46\u8981\u6C42\u552F\u4E00\uFF0C\u5EFA\u8BAE\u914D\u5408\u670D\u52A1\u540D
          #uri: http://127.0.0.1:8001
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**  #\u65AD\u8A00\uFF0C\u8DEF\u5F84\u76F8\u5339\u914D\u7684\u8FDB\u884C\u8DEF\u7531
            - After=2020-10-26T14:34:52.576+08:00[Asia/Shanghai]
            #- Before=2020-10-26T14:34:52.576+08:00[Asia/Shanghai]
            #- Between=2020-10-26T14:34:52.576+08:00[Asia/Shanghai],2020-10-26T14:39:52.576+08:00[Asia/Shanghai]
            - Cookie=username,yds #key value形式，value写正则表达式
            - Header=X-Request-Id,\d+ #请求头要有X-Request-Id属性并且值为整数的正则表达式

        - id: payment_routh3
          #uri: http://127.0.0.1:8001
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址 lb负载均衡的意思
          predicates:
            - Path=/payment/**
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: gateway
