server:
  # consul\u670D\u52A1\u7AEF\u53E3
  port: 8006
spring:
  application:
    name: cloud-provider-payment
  cloud:
    consul:
      # consul\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
      host: 192.168.17.131
      port: 8500
      discovery:
        hostname: 192.168.17.131
        service-name: ${spring.application.name}