server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://192.168.17.131:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
#    schema:
#      - classpath:sql/db.sql
#    initialization-mode: always
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.atguigu.cloudapicommons.entity

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    #注册到eureka中  默认为ture
    register-with-eureka: true
    #是否从eurekaServer中抓取信息，单点无所谓，集群必须为true才能配合ribbon使用负载均衡，默认为true
    fetch-registry: true