server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://192.168.17.131:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
#    schema:
#      - classpath:sql/db.sql
#    initialization-mode: always

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.atguigu.entity