server:
  port: 7001
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    #false\u8868\u793A\u4E0D\u5411\u6CE8\u518C\u4E2D\u5FC3\u6CE8\u518C\u81EA\u5DF1
    register-with-eureka: false
    #\u4E0D\u53BB\u68C0\u7D22\u81EA\u5DF1
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/